import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div 
      className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      style={{ backgroundColor: "#e2e3e5", height: "100%" }}
    >
      <div className="jil_adm_top_wrap">
        <div className="jil_adm_hdr_title">신청자 관리</div>
        <div style={{ textAlign: "right" }}>
          <Link href="/wadm/slist" className="jil_adm_t_btn jil_adm_mr_2">관리자 홈</Link>
          <Link href="/" className="jil_adm_t_btn_logout jil_adm_mr_2">사용자 홈</Link>
          <Link href="/wadm/excelupload" className="jil_adm_t_btn_logout jil_adm_mr_2">엑셀(대)</Link>
          <Link href="/wadm/exceluploadmid" className="jil_adm_t_btn_logout jil_adm_mr_2">엑셀(고)</Link>
        </div>
      </div>

      <div className="jil_adm_hdr_wrap">
        <div>&nbsp;</div>
        <div className="jil_adm_hdr_mid bg-secondary-subtle">
          <Link href="/wadm/slist" className="jil_adm_menu_lk jil_adm_mr_2">성취장학금</Link>
          <Link href="/wadm/sjlist" className="jil_adm_menu_lk jil_adm_mr_2">재능장학금</Link>
          <Link href="/wadm/shlist" className="jil_adm_menu_lk jil_adm_mr_2">희망장학금</Link>
          <Link href="/wadm/period" className="jil_adm_menu_lk jil_adm_mr_2">신청기간 설정</Link>
        </div>
        <div>&nbsp;</div>
      </div>

      {children}
    </div>
  );
}
